# Generated by Django 5.2.2 on 2025-06-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('speciality', models.CharField(max_length=255, verbose_name='Специальность')),
                ('room', models.IntegerField(verbose_name='Кабинет')),
                ('time', models.TimeField(verbose_name='Время приёма')),
            ],
            options={
                'verbose_name': 'Данные врача',
                'verbose_name_plural': 'Данные врачей',
            },
        ),
    ]
