# Generated by Django 5.2.2 on 2025-06-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_data',
            name='room',
            field=models.IntegerField(unique=True, verbose_name='Кабинет'),
        ),
    ]
